weights: /content/yolov7_udp/yolov7-tiny.weights
cfg: /content/drive/MyDrive/IEEE_Access/code/yolov7_udp/cfg/training/yolov7-tiny_udp.yaml
data: /content/drive/MyDrive/IEEE_Access/code/yolov9_udp/data/udp_yaml
hyp: /content/drive/MyDrive/IEEE_Access/code/yolov7_udp/data/hyp.scratch.tiny_udp.yaml
epochs: 100
batch_size: 350
img_size:
- 320
- 320
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: /content/drive/MyDrive/IEEE_Access/code/yolov7_udp/runs/train/
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: /content/drive/MyDrive/IEEE_Access/code/yolov7_udp/runs/train/exp2
total_batch_size: 350
